name: GitHub-Profile-Summary-Cards

on:
  schedule: # Se ejecuta automáticamente cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Te permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v3
      - uses: vn7n24fzkq/Github-Profile-Summary-Cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PROFILE_SUMMARY_CARD }}
        with:
          USERNAME: ${{ github.repository_owner }}
